language: python
cache: pip
dist: xenial

services:
  - postgresql
addons:
    postgresql: "10"

matrix:
  include:
    # Wagtail 2.7 LTS
    # Django 2.0
    - env: TOXENV=py35-dj20-wt27
      python: 3.5
    - env: TOXENV=py36-dj20-wt27
      python: 3.6
    - env: TOXENV=py37-dj20-wt27
      python: 3.7
    - env: TOXENV=py38-dj20-wt27
      python: 3.8
    
    # Django 2.1
    - env: TOXENV=py35-dj21-wt27
      python: 3.5
    - env: TOXENV=py36-dj21-wt27
      python: 3.6
    - env: TOXENV=py37-dj21-wt27
      python: 3.7
    - env: TOXENV=py38-dj21-wt27
      python: 3.8

    # Django 2.2
    - env: TOXENV=py35-dj22-wt27
      python: 3.5
    - env: TOXENV=py36-dj22-wt27
      python: 3.6
    - env: TOXENV=py37-dj22-wt27
      python: 3.7
    - env: TOXENV=py38-dj22-wt27
      python: 3.8


    # Wagtail 2.8
    # Django 2.1
    - env: TOXENV=py35-dj21-wt28
      python: 3.5
    - env: TOXENV=py36-dj21-wt28
      python: 3.6
    - env: TOXENV=py37-dj21-wt28
      python: 3.7
    - env: TOXENV=py38-dj21-wt28
      python: 3.8
    
    # Django 2.2
    - env: TOXENV=py35-dj22-wt28
      python: 3.5
    - env: TOXENV=py36-dj22-wt28
      python: 3.6
    - env: TOXENV=py37-dj22-wt28
      python: 3.7
    - env: TOXENV=py38-dj22-wt28
      python: 3.8

    # Django 3.0
    - env: TOXENV=py36-dj30-wt28
      python: 3.6
    - env: TOXENV=py37-dj30-wt28
      python: 3.7
    - env: TOXENV=py38-dj30-wt28
      python: 3.8

    # Wagtail 2.9  
    # Django 2.2
    - env: TOXENV=py35-dj22-wt29
      python: 3.5
    - env: TOXENV=py36-dj22-wt29
      python: 3.6
    - env: TOXENV=py37-dj22-wt29
      python: 3.7
    - env: TOXENV=py38-dj22-wt29
      python: 3.8

    # Django 3.0
    - env: TOXENV=py36-dj30-wt29
      python: 3.6
    - env: TOXENV=py37-dj30-wt29
      python: 3.7
    - env: TOXENV=py38-dj30-wt29
      python: 3.8
    
    # Wagtail 2.10
    # Django 2.2
    - env: TOXENV=py36-dj22-wt210
      python: 3.6
    - env: TOXENV=py37-dj22-wt210
      python: 3.7
    - env: TOXENV=py38-dj22-wt210
      python: 3.8

    # Django 3.0
    - env: TOXENV=py36-dj30-wt210
      python: 3.6
    - env: TOXENV=py37-dj30-wt210
      python: 3.7
    - env: TOXENV=py38-dj30-wt210
      python: 3.8
    
    # Django 3.1
    - env: TOXENV=py36-dj31-wt210
      python: 3.6
    - env: TOXENV=py37-dj31-wt210
      python: 3.7
    - env: TOXENV=py38-dj31-wt210
      python: 3.8

    # Flake 8
    - env: TOXENV=flake8
      python: 3.7

  allow_failures:
    # wagtail dev
    - env: TOXENV=wagtaildev
      python: 3.7

# Package installation
install:
  - pip install codecov tox

# Run the tests
script:
  - tox -e $TOXENV

# After the tests
after_success:
  - codecov
